//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentTable
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> TaskOwnerID { get; set; }
        public Nullable<System.DateTime> AssignmentDateTime { get; set; }
        public Nullable<decimal> ActualDuration { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<decimal> BillableHours { get; set; }
        public Nullable<int> IsBillableApproved { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> BillableApprovedDateTime { get; set; }
        public Nullable<int> IsActualApproved { get; set; }
        public Nullable<int> UserIDActual { get; set; }
        public Nullable<System.DateTime> ActualApprovedDateTime { get; set; }
        public Nullable<int> MainTaskID { get; set; }
    
        public virtual SubTaskTable SubTaskTable { get; set; }
    }
}
