//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientTable
    {
        public int ID { get; set; }
        public string ClientName { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string Website_URL { get; set; }
        public string Facebooklink { get; set; }
        public string Twitter { get; set; }
        public string instagramlink { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
