//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentMapping
    {
        public int DepartMappingID { get; set; }
        public int DepartID { get; set; }
        public int MaintaskID { get; set; }
        public Nullable<bool> AdditionalCheck { get; set; }
    }
}
