//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormattedScrappedData
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string DataChunk { get; set; }
        public string Country { get; set; }
        public string Department { get; set; }
        public string Company { get; set; }
        public string MessageType { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Source { get; set; }
    }
}
