//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTable
    {
        public int iNotificationId { get; set; }
        public Nullable<int> iProjectId { get; set; }
        public Nullable<System.DateTime> dtCreation { get; set; }
    }
}
