//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleReport_Updates
    {
        public int SchReport_UpdateID { get; set; }
        public string Update_ { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Comments { get; set; }
        public string Phase { get; set; }
    }
}
