//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskNotFoundTable
    {
        public int ID { get; set; }
        public string ProjectID { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<int> TaskOwnerID { get; set; }
        public Nullable<System.DateTime> AssignmentDateTime { get; set; }
        public Nullable<decimal> ActualDuration { get; set; }
        public string SubTaskDescription { get; set; }
    }
}
