//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class URLShortnerMappingTable
    {
        public int ID { get; set; }
        public string Company { get; set; }
        public string EmailAddress { get; set; }
        public string ActualURL { get; set; }
        public string ShortURL { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
        public string PageTitle { get; set; }
        public Nullable<int> LinkOpenCount { get; set; }
        public string SessionID { get; set; }
    }
}
