//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class URLShortnerMappingAttributeDetail
    {
        public int ID { get; set; }
        public Nullable<int> ShortUrlID { get; set; }
        public string BrowserName { get; set; }
        public string OSname { get; set; }
        public string Language { get; set; }
        public string DeviceName { get; set; }
    }
}
