//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int Userid { get; set; }
        public Nullable<int> Loginid { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Joiningdate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string EMSRole { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> Creationdatetime { get; set; }
        public string Designation { get; set; }
    }
}
