//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int NotificationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string NotificationMessage { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public string isRead { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public string NotificationHeader { get; set; }
        public Nullable<bool> isSeen { get; set; }
    }
}
